services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    environment:
      NODE_ENV: "development"
      DATABASE_URL: "postgresql://docker:docker@postgres:5432/polls"
      PORT: "3333"
    command: >
      sh -c "npx prisma generate && npx tsx watch ./http/src/server.ts"
    volumes:
      - ./http/uploads:/app/http/uploads
      - ./prisma:/app/prisma
      - ./http:/app/http

  frontend:
    build:
      context: ../web
    container_name: web
    ports:
      - "5173:5173"
    environment:
      - VITE_PORT=5173
    volumes:
      - ../web:/app
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - backend

  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=polls
    volumes:
      - polls_pg_data:/bitnami/postgresql

volumes:
  polls_pg_data:
networks:
  backend:
    driver: bridge
